title: Roberto Andrade
logo: "/images/image.png" 
description: >
  Business Analytics Candidate at the University of Notre Dame
contact: >
  <a href="https://www.linkedin.com/in/roberto-andrade-martinez">LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/roberto-andrade22">GitHub Profile</a>
  <br><br>
  <a href='resume'>Résumé</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
