title: Roberto Andrade
logo: "/images/image.jpg?raw=true" 
description: >   Business Analytics Student at the University of Notre Dame  
  <br><br>
  <a href="https://www.linkedin.com/in/roberto-andrade-martinez//">LinkedIn Profile</a> 
  <a href="https://github.com/roberto-andrade22">GitHub Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
