title: Roberto Andrade
logo: "/images/DSC06712.JPG" 
description: >
  Market Modeling Analyst at AFRY Management Consulting
contact: >
  <a href="https://www.linkedin.com/in/roberto-andrade-martinez">LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/roberto-andrade22">GitHub Profile</a>
  <br><br>
  <a href='resume'>Résumé</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
